version: '3.5'  

services:

  frontend: 
    image: frontend
    container_name: frontend

  backend: 
    image: backend
    environment:
      - FRONT_URL=http://frontend:5000
    container_name: backend

  proxy:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports: 
      - 80:80
    environment: 
      - NGINX_PORT=80
    container_name: proxy