version: '3.5'

services:

  frontend:
    build: ./ml-kurkkumopo-frontend
    image: ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:5000

  backend:
    build: ./ml-kurkkumopo-backend
    image: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    environment:
      - FRONT_URL=http://localhost:3000
    volumes: 
      - training:/src/model
    depends_on:
      - training

  training:
    build: ./ml-kurkkumopo-training
    image: ml-kurkkumopo-training
    volumes: 
      - model:/model
      - /src/imgs:/imgs

volumes:
  model:
  training:
  images: